name: workflows_login

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 10-19 * * 1-5'
jobs:
  install-dependence:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
  execution-tests-api:
    needs: install-dependence
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: All Test
        uses: actions/checkout@v2

      - name: Run end-to-end tests on desktop 🧪
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
        with:
          command: npx cypress run --env grepTags=@login
      - name: Upload Artifact GitHub Action
        run: cd ./cypress/reports/html/
      - uses: actions/upload-artifact@v3
        if: failure()
        with: 
          name: Artifact
          path: ./cypress/reports
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_TITLE: Automation Test WEB
          SLACK_MESSAGE: 'Some tests failed, please review the logs by clicking the link above!'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_AUT_WEB }}
          SLACK_COLOR: '#FF0000'
